### ISSUE TITLE
使用mysql时，在linux环境下报错

### ISSUE THREAD

**Issue by bylijinnan** [xuhuisheng/lemon#101]
发起一个“请假流程”，报错：Table 'lemon.bpm_delegate_info' doesn't exist

原因是mysql在linux当中的表名是区分大小写的，而默认的建表语句里表名是大写，但代码里表名是小写：
public class DelegateService {
    private static Logger logger = LoggerFactory
            .getLogger(DelegateService.class);
    public static final String SQL_GET_DELEGATE_INFO = "select * from bpm_delegate_info"
            + " where status=1 and assignee=? order by id desc";

**Comment by xuhuisheng** [comment]
新版本直接换用hibernate，算是间接修复了。
