### ISSUE TITLE
java类中有很多无效的类引用声明

### ISSUE THREAD

**Issue by maosi** [xuhuisheng/lemon#103]
在eclipse可通过`ctrl+shift+o`删除无效的impot并重新组织导入.或者在`Package Explorer`等视图中右键项目 --> source --> orgnize imports,这样可以将整个项目的无效import都删除.

![a](https://cloud.githubusercontent.com/assets/3891505/5694475/1c722a48-9998-11e4-94f8-147043474e7a.jpg)

**Comment by xuhuisheng** [comment]
求贡献啊

**Comment by xuhuisheng** [comment]
已经按照提示的方法删除了所有unused import
https://github.com/xuhuisheng/lemon/commit/0c5ba3409b1b064d09a61a009d91d6a17b3119d6
