### ISSUE TITLE
菜单链接问题

### ISSUE THREAD

**Issue by xvweirong** [xuhuisheng/lemon#113]
V1.6.0 下面菜单的链接都有问题：
统计报表 http://report/chart-mostActiveProcess.do
账号管理 http://user/account-info-list.do
群组管理 http://group/group-info-list.do
权限管理 http://auth/user-status-list.do
会话管理 http://user/account-online-list.do

**Comment by xuhuisheng** [comment]
因为自动生成菜单时，多写了几个///，导致所有链接都变成根目录了。
已经修复https://github.com/xuhuisheng/lemon/commit/369438b6d8dbd3a58ebbd706e8e085ff54ece54d
