### ISSUE TITLE
tomcat部署时内存溢出

### ISSUE THREAD

**Issue by huisongyang** [xuhuisheng/lemon#120]
用tomcat6部署的时候，报内存溢出的错误。

**Comment by xuhuisheng** [comment]
内存溢出问题

启动之后，出现OutOfMemoryError: PermGen

解决方法是：设置JAVA_OPTS=-Xms1024M -Xmx1024M -XX:PermSize=256M -XX:MaxPermSize=256M，加大Perm内存。
