### ISSUE TITLE
openJDK8 报错 java.lang.CharSequence cannot be resolved

### ISSUE THREAD

**Issue by weibangtuo** [xuhuisheng/lemon#122]
Linux下JDK8编译，部分页面报这个错，导致页面显示空白无法打开。

希望兼容到JDK8，现在JDK9都出来了，不能太落后了！

**Comment by xuhuisheng** [comment]
为啥找不到CharSequence这个类呢？看api里有这个类哟，挺奇怪的。

**Comment by xuhuisheng** [comment]
发现是jetty-6.x不支持java8。
暂时的解决方案是换成java7。
后续的解决方案会在maven里判断java版本使用不同版本的jetty。
一键运行包要分成java7和java8两个版本了。

**Comment by longfan3** [comment]
换成jetty-8.X就行
