### ISSUE TITLE
下载后直接导入各种报错

### ISSUE THREAD

**Issue by gaohuaiyun** [xuhuisheng/lemon#136]
如题，下的是1.7版本的。大多是两种错：1.BeanCreationException,2.NoClassDefFoundError。用的是eclipse+jdk1.6+maven。你们没用到过吗？求帮助，help me please ，all of yuo!

**Comment by gaohuaiyun** [comment]
Caused by: java.lang.NoClassDefFoundError: org/activiti/engine/impl/cfg/ProcessEngineConfigurationImpl这是什么鬼？为啥我没找到cfg路径呢

**Comment by xuhuisheng** [comment]
请提供详细日志，spring因为反射，所以日志会特别多。
从你说的找不到类的异常来看，可能是maven下载依赖失败，找个好点儿的网络，多试几次吧。

**Comment by gaohuaiyun** [comment]
比如其中一个，在/lemon/src/main/resources/spring/ctx-common-filter.xml文件中的一个配置<property name="filter" ref="springSecurityFilterChain"/>，springSecurityFilterChain就没有找到在哪配置的

**Comment by xuhuisheng** [comment]
在maven中配置了spring security的依赖，如果报告找不到依赖，说明网络问题导致下载失败。需要换更快的网络。
