### ISSUE TITLE
数据库

### ISSUE THREAD

**Issue by isushao** [xuhuisheng/lemon#138]
org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'hsqldbServer' defined in file [E:\Program files\apache-tomcat-8.0.43\webapps\lemon-master\WEB-INF\classes\spring\ctx-common-jdbc.xml]: Could not resolve placeholder 'hsqldb.enabled' in string value "${hsqldb.enabled}"; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'hsqldb.enabled' in string value "${hsqldb.enabled}"

**Comment by xuhuisheng** [comment]
不要删除配置文件里的hsqldb.enabled
