### ISSUE TITLE
邮箱问题

### ISSUE THREAD

**Issue by isushao** [xuhuisheng/lemon#143]
请问，如何配置才能用户之间发送邮件呢

**Comment by xuhuisheng** [comment]
smtp服务器配置好，就可以发邮件了

**Comment by isushao** [comment]
没太明白 实在系统内配置还是本地配置

**Comment by xuhuisheng** [comment]
![default](https://cloud.githubusercontent.com/assets/1118508/26237721/e84299b8-3ca8-11e7-8757-c65753a00d83.png)
系统的个人邮箱部分，可以配置

**Comment by isushao** [comment]
我配置这个了  还是发不了啊

**Comment by isushao** [comment]
点击发送后已发送没有  对方也没收到

**Comment by isushao** [comment]
![image](https://cloud.githubusercontent.com/assets/16602760/26238746/009d6bf6-3cad-11e7-80b4-2971fc95cac6.png)

**Comment by isushao** [comment]
![image](https://cloud.githubusercontent.com/assets/16602760/26276238/d784feba-3da5-11e7-8656-7fef66cc702b.png)

**Comment by xuhuisheng** [comment]
mossle.com的邮件服务因为服务器资源不足，早已关闭了。
你可以使用一个正在运行的smtp服务
