### ISSUE TITLE
centos下tomcat启动报错如下，window下调试则正常。请问这是什么原因导致的？

### ISSUE THREAD

**Issue by boxingYi** [xuhuisheng/lemon#153]
BeanCreationException: Error creating bean with name 'processEngine' defined in file [/data/tomcat/servers/case/webapps/lemon/WEB-INF/classes/spring/ctx-module-activiti.xml]: Invocation of init method failed; nested exception is org.activiti.engine.ActivitiException: transactionManager is required property for SpringProcessEngineConfiguration, use org.activiti.engine.impl.cfg.StandaloneProcessEngineConfiguration otherwise

**Comment by xuhuisheng** [comment]
大概率数据库没连上
因为报错说transactionManager注入失败

**Comment by lihuan215** [comment]
问题解决了吗？MacOS下也出现同样的问题，调试两天了解决不掉

**Comment by xuhuisheng** [comment]
你们要学会提问的智慧，至少把完整错误信息提供出来。
