### ISSUE TITLE
按照官网说的进行到  生成独立运行包 mvn package -Pstandalone，结果无法找到assembly-standalone.xml

### ISSUE THREAD

**Issue by chrisyxg** [xuhuisheng/lemon#155]
按照官网说的进行到  生成独立运行包 mvn package -Pstandalone，结果无法找到assembly-standalone.xml

**Comment by xuhuisheng** [comment]
文档已经过期，不再支持独立运行包了，请mvn package生成war，放到tomcat之类的服务器下运行。
