### ISSUE TITLE
无法正常登陆

### ISSUE THREAD

**Issue by horizon999** [xuhuisheng/lemon#158]
【问题1】：
登陆用户名lingo,密码：1 登陆后(用king/1登陆也有同样的问题)，提示：
com.mossle.security.util.SpringSecurityListener:207 - org.springframework.security.authentication.UsernamePasswordAuthenticationToken@6211aef: Principal: lingo; Credentials: [PROTECTED]; Authenticated: false; Details: org.springframework.security.web.authentication.WebAuthenticationDetails@255f8: RemoteIpAddress: 192.168.0.106; SessionId: 7c0b093b-bf79-445c-9c8c-dcfbc80b3c68; Not granted any authorities
【问题2】
登陆失败显示为乱码
![default](https://user-images.githubusercontent.com/33595300/32698193-fb8f877e-c7db-11e7-9a3d-47dc1476e09d.png)

**Comment by xuhuisheng** [comment]
参考：
https://github.com/xuhuisheng/lemon/commit/bf1632c96164e088341f951ad3f308983d5516f9

**Comment by horizon999** [comment]
已解决，谢谢。@xuhuisheng
