### ISSUE TITLE
请问将项目的数据库由默认的HSQL变更为MySQL时，Spring文件夹下的配置文件的depen-on应该怎么改？

### ISSUE THREAD

**Issue by YoWenhow** [xuhuisheng/lemon#160]
如在ctx-common-jdbc.xml文件中，
`	
	<bean id="databaseMigrator" class="com.mossle.core.dbmigrate.DatabaseMigrator" depends-on="hsqldbServer">
		<property name="dataSource" ref="dataSource"/>
		<property name="enabled" value="${dbmigrate.enabled}"/>
		<property name="clean" value="${dbmigrate.clean}"/>
	</bean>`
这里的depends-on应当修改为什么？

**Comment by xuhuisheng** [comment]
如果有洁癖的话，可以去掉depends-on。
因为已经在配置文件中设置了关闭hsqldbServer的自动启动，所以保留depends-on也不会有影响。

**Comment by YoWenhow** [comment]
感谢回答！保留depends-on的情况下启动时会报无法创建bean的错误，去除后正常。另外请问从哪边更新一下数据的时间，项目启动后登陆提示密码过期。

**Comment by xuhuisheng** [comment]
https://github.com/xuhuisheng/lemon/commit/bf1632c96164e088341f951ad3f308983d5516f9
