### ISSUE TITLE
新建模型404

### ISSUE THREAD

**Issue by 17722623782** [xuhuisheng/lemon#161]
我想看看在线设计表单和流程图，但是点按钮就404了，无法在线增加流程
![image](https://user-images.githubusercontent.com/33513950/34476906-f9594564-efcf-11e7-9b3b-656c6851d841.png)
![image](https://user-images.githubusercontent.com/33513950/34476911-036b469c-efd0-11e7-8b13-5c707cc3130d.png)

**Comment by xuhuisheng** [comment]
https://github.com/xuhuisheng/lemon/commit/28f8685393dcf83bdd5744e9c0ae4a801770561b
