### ISSUE TITLE
显示案例异常

### ISSUE THREAD

**Issue by hengzheoduyou** [xuhuisheng/lemon#164]
lemon-1.8.0.zip 显示数据库设置的帐号密码过期，登录需要修改密码，但是修改密码的common/change-password.jsp页面不存在，所以示例没法跑，可能要调整示例数据。

**Comment by xuhuisheng** [comment]
参考此处修改
https://github.com/xuhuisheng/lemon/commit/bf1632c96164e088341f951ad3f308983d5516f9
