### ISSUE TITLE
1.8两个类，包名称不对

### ISSUE THREAD

**Issue by hengzheoduyou** [xuhuisheng/lemon#166]
不知道是不是1.9发布动到了。之前好像正常

 "com.mossle.humantask.web.portal" does not match the expected package "com.mossle.msg.web.portal"	MsgPortalController.java	/lemon/src/main/java/com/mossle/msg/web/portal	

 "com.mossle.internal.whitelist.web.admin" does not match the expected package "com.mossle.internal.whitelist.web.user"	WhitelistUserController.java	/lemon/src/main/java/com/mossle/internal/whitelist/web/user

**Comment by xuhuisheng** [comment]
参考最新的1.9.0的代码吧。

https://github.com/xuhuisheng/lemon/blob/master/src/main/java/com/mossle/msg/web/portal/MsgPortalController.java 包名没有com.mossle.humantask.web.portal
whitelist包暂时去掉了，因为目前没有用。

**Comment by hengzheoduyou** [comment]
直接把包名改了，1.8和1.9代码分开看的。1.8其他也没什么问题。

**Comment by xuhuisheng** [comment]
1.9这部分应该没问题。先关闭，如果有问题可以重开。
