### ISSUE TITLE
流程无法接收

### ISSUE THREAD

**Issue by Downupanddownup** [xuhuisheng/lemon#168]
自定义一个流程，指定某人（如king）为负责人或候选人，启动流程后，改人没有接收到流程。有人知道怎么解决吗？

**Comment by Downupanddownup** [comment]
在添加king为负责人后，显示的行的名称是一串数字（46155369775104），不知道正不正确。

**Comment by xuhuisheng** [comment]
估计是bug，1.9.0开始使用code，而不是id了。我复查一下。

**Comment by Downupanddownup** [comment]
好的，辛苦啦
