### ISSUE TITLE
职位无法配置

### ISSUE THREAD

**Issue by Downupanddownup** [xuhuisheng/lemon#170]
![image](https://user-images.githubusercontent.com/12596230/44010691-90ce1d8c-9ee6-11e8-8cc7-ed7c46a7f08a.png)
![image](https://user-images.githubusercontent.com/12596230/44010700-9fbb3942-9ee6-11e8-9c3d-48eb7449d34c.png)

**Comment by Downupanddownup** [comment]
上面不是写了用户吗？

**Comment by xuhuisheng** [comment]
修复了
