### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by Downupanddownup** [xuhuisheng/lemon#171]
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /D:/lemon/2018-08-15/lemon-master/src/main/java/com/mossle/party/web/OrgController.java:[9,30] 程序包com.mossle.client.user不存在
[ERROR] /D:/lemon/2018-08-15/lemon-master/src/main/java/com/mossle/party/web/OrgController.java:[49,13] 找不到符号
  符号:   类 UserClient
  位置: 类 com.mossle.party.web.OrgController
[ERROR] /D:/lemon/2018-08-15/lemon-master/src/main/java/com/mossle/party/web/OrgController.java:[513,31] 找不到符号
  符号:   类 UserClient
  位置: 类 com.mossle.party.web.OrgController
[INFO] 3 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 19.244 s
[INFO] Finished at: 2018-08-15T14:34:05+08:00
[INFO] Final Memory: 24M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project lemon: Compilation failure: Compilation failure: 
[ERROR] /D:/lemon/2018-08-15/lemon-master/src/main/java/com/mossle/party/web/OrgController.java:[9,30] 程序包com.mossle.client.user不存在
[ERROR] /D:/lemon/2018-08-15/lemon-master/src/main/java/com/mossle/party/web/OrgController.java:[49,13] 找不到符号
[ERROR]   符号:   类 UserClient
[ERROR]   位置: 类 com.mossle.party.web.OrgController
[ERROR] /D:/lemon/2018-08-15/lemon-master/src/main/java/com/mossle/party/web/OrgController.java:[513,31] 找不到符号
[ERROR]   符号:   类 UserClient
[ERROR]   位置: 类 com.mossle.party.web.OrgController
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by xuhuisheng** [comment]
已回滚错误代码
