### ISSUE TITLE
请问www.mossle.com登录账号密码是什么

### ISSUE THREAD

**Issue by gxbcj** [xuhuisheng/lemon#190]
@xuhuisheng，你好，想在官网看下产品的资料，都需要登录后才能查看的，默认的账号密码好像不起效，想问下现在的账号密码是多少

**Comment by xuhuisheng** [comment]
线上有人把密码改了。
已经改回1了。

**Comment by gxbcj** [comment]
是 lingo/1  吗？
好像还是不行啊

**Comment by gxbcj** [comment]
> 线上有人把密码改了。
> 已经改回1了。

lingo / 1 吗，还是不行呢...
