### ISSUE TITLE
DatabaseKeyValue删除草稿应该带级联删除

### ISSUE THREAD

**Issue by yuewxuing** [xuhuisheng/lemon#92]
/**
     * 根据code删除记录.
     */
    public void removeByCode(String code) {
        jdbcTemplate.update("delete from KV_PROP where record_id=?", code);
        jdbcTemplate.update("delete from KV_RECORD where id=?", code);
    }

**Comment by xuhuisheng** [comment]
已修复
https://github.com/xuhuisheng/lemon/commit/139cb9b57c1ad1f2c98943075bfd49ac436a6898
